#main program
import files
import exceptions

#files.employee_filing('file.txt')

#files.read_records('file.txt')

'''result = exceptions.divide_a_number(2,0)

print(result)'''


#exceptions.multiple_2_numbers()

#exceptions.open_fake_file()